name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push emane-python image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: core/dockerfiles/Dockerfile.emane-python
          push: true
          tags: ghcr.io/${{ github.repository }}:emane-python

      - name: Build and push ospf-mdr-rpm image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: core/dockerfiles/Dockerfile.ospf-mdr-rpm
          push: true
          tags: ghcr.io/${{ github.repository }}:ospf-mdr-rpm
          build-args: |
            FROM_IMAGE=ghcr.io/${{ github.repository }}:emane-python

      - name: Build and push rocky image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: core/dockerfiles/Dockerfile.rocky
          push: true
          tags: ghcr.io/${{ github.repository }}:rocky
          build-args: |
            FROM_IMAGE=ghcr.io/${{ github.repository }}:ospf-mdr-rpm

      - name: Build and push ospf-mdr-deb image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: core/dockerfiles/Dockerfile.ospf-mdr-deb
          push: true
          tags: ghcr.io/${{ github.repository }}:ospf-mdr-deb
          build-args: |
            FROM_IMAGE=ghcr.io/${{ github.repository }}:emane-python

      - name: Build and push ubuntu image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: core/dockerfiles/Dockerfile.ubuntu
          push: true
          tags: ghcr.io/${{ github.repository }}:ubuntu
          build-args: |
            FROM_IMAGE=ghcr.io/${{ github.repository }}:ospf-mdr-deb
