name: Build and Push Docker Images

on:
  push:
    branches:
      - master

jobs:
  build-and-push-emane-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push emane-python image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: dockerfiles/Dockerfile.emane-python
          push: true
          tags: ghcr.io/${{ github.repository }}:emane-python

  build-and-push-ospf-mdr-rpm:
    runs-on: ubuntu-latest
    needs: build-and-push-emane-python
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ospf-mdr-rpm image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: dockerfiles/Dockerfile.ospf-mdr-rpm
          push: true
          tags: ghcr.io/${{ github.repository }}:ospf-mdr-rpm

  build-and-push-ospf-mdr-deb:
    runs-on: ubuntu-latest
    needs: build-and-push-emane-python
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ospf-mdr-deb image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: dockerfiles/Dockerfile.ospf-mdr-deb
          push: true
          tags: ghcr.io/${{ github.repository }}:ospf-mdr-deb

  build-and-push-rocky:
    runs-on: ubuntu-latest
    needs: build-and-push-ospf-mdr-rpm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push rocky image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: dockerfiles/Dockerfile.rocky
          push: true
          tags: ghcr.io/${{ github.repository }}:rocky

  build-and-push-ubuntu:
    runs-on: ubuntu-latest
    needs: build-and-push-ospf-mdr-deb
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ubuntu image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: dockerfiles/Dockerfile.ubuntu
          push: true
          tags: ghcr.io/${{ github.repository }}:ubuntu
